In [1]:
#We start with the imports and installs:

!pip install pandas sklearn xgboost
from __future__ import print_function
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib as plt

Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.5)
Requirement already satisfied: sklearn in /usr/local/lib/python3.7/dist-packages (0.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.7/dist-packages (0.90)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.19.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (from sklearn) (1.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from xgboost) (1.4.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->sklearn) (3.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->sklearn) (1.1.0)

In [2]:
#let's download the dataset:

!gdown https://archive.ics.uci.edu/ml/machine-learning-databases/parkinsons/parkinsons.data

Downloading...
From: https://archive.ics.uci.edu/ml/machine-learning-databases/parkinsons/parkinsons.data
To: /content/parkinsons.data
100% 40.7k/40.7k [00:00<00:00, 1.88MB/s]

In [3]:
# Read the data using Pandas to display the columns. First, we use the describe function to show usefull statistics and information about the dataset.
df = pd.read_csv('/content/parkinsons.data', sep=",")
df.describe()

       MDVP:Fo(Hz)  MDVP:Fhi(Hz)  ...          D2         PPE
count   195.000000    195.000000  ...  195.000000  195.000000
mean    154.228641    197.104918  ...    2.381826    0.206552
std      41.390065     91.491548  ...    0.382799    0.090119
min      88.333000    102.145000  ...    1.423287    0.044539
25%     117.572000    134.862500  ...    2.099125    0.137451
50%     148.790000    175.829000  ...    2.361532    0.194052
75%     182.769000    224.205500  ...    2.636456    0.252980
max     260.105000    592.030000  ...    3.671155    0.527367

[8 rows x 23 columns]

In [4]:
# the head() function prints the first 5 rows of the dataset.
df.head()

             name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  ...   spread2        D2       PPE
0  phon_R01_S01_1      119.992       157.302  ...  0.266482  2.301442  0.284654
1  phon_R01_S01_2      122.400       148.650  ...  0.335590  2.486855  0.368674
2  phon_R01_S01_3      116.682       131.111  ...  0.311173  2.342259  0.332634
3  phon_R01_S01_4      116.676       137.871  ...  0.334147  2.405554  0.368975
4  phon_R01_S01_5      116.014       141.781  ...  0.234513  2.332180  0.410335

[5 rows x 24 columns]

In [12]:
# This tells us how many rows the dataset has:
count_row = df.shape[0]
print(f"This dataset is {count_row} rows long.")

This dataset is 195 rows long.

In [13]:
# Get the count of each label (0 and 1) in labels
print(f"The number of positive and negative labels is: {labels[labels == 1].shape[0], labels[labels == 0].shape[0]}")

The number of positive and negative labels is: (147, 48)

In [6]:
# Let's get the features and labels: the status column will act as label: 1 is parkinson positive, 0 is negative.
features = df.loc[:, df.columns != 'status'].values[:, 1:]
labels = df.loc[:, 'status'].values

In [8]:
# Scale the features between -1 and 1:
scaler = MinMaxScaler((-1, 1))
x = scaler.fit_transform(features)
y = labels

# Split the dataset between Training and Test sets. The test set will be 20% of the overall dataset. Also, we will shuffle the row to avoid bias:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=7)

In [ ]:
# Train the model using XGB Classifier
model = XGBClassifier()

# define the eval set and metric
eval_set = [(x_train, y_train), (x_test, y_test)]
eval_metric = ["auc","error"]

# We fit the model (verbosity can be set to False to avoid the full epochs' log)
model.fit(x_train, y_train, eval_metric=eval_metric, eval_set=eval_set, verbose=True)

In [15]:
# Last, we calculate the model's accuracy using the .predict function:
test_pred = model.predict(x_test)
train_pred = model.predict(x_train)
print('Train Accuracy: ', accuracy_score(y_train, train_pred))
print('Test Accuraccy: ', accuracy_score(y_test, test_pred))
print("\n")
print(f"The model's actual accuracy is {accuracy_score(y_test, test_pred) * 100} %")

Train Accuracy:  1.0
Test Accuraccy:  0.9487179487179487


The model's actual accuracy is 94.87179487179486 %